language: php

sudo: required
    
services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

addons:
  postgresql: "9.6"
  apt:
    packages:
      - openjdk-8-jre-headless

php:
 - 5.6
 - 7.0
 - 7.1
 - 7.2

env:

  matrix:
    - DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE

matrix:
  exclude:      
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
      php: 5.6
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
      php: 5.6
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
      php: 5.6
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
      php: 5.6
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
      php: 7.0
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
      php: 5.6
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
      php: 5.6
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
      php: 5.6
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
      php: 5.6
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
      php: 7.0

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat

  